# Add files to the system, all have been base64 encoded to avoid issues with special characters
write_files:
  # Update rkhunter.conf to enable automatic updates
  - path: /usr/local/bin/update-rkhunter-conf.sh
    encoding: b64
    owner: root:root
    permissions: '0755'
    content: |
      ${update_rkhunter_conf}
  # Write a basic AIDE configuration file
  - path: /etc/aide/aide.conf
    encoding: b64
    owner: root:root
    permissions: '0644'
    content: |
      ${aide_conf}
  # Update netplan to not use dhcp dns
  - path: /etc/netplan/01-netcfg.yaml
    encoding: b64
    owner: root:root
    permissions: '0644'
    content: |
      ${netcfg}
  # Update network
  - path: /etc/systemd/network/05-eth0.network
    encoding: b64
    owner: root:root
    permissions: '0644'
    content: |
      ${eth0_network}
  # Automatically logout inactive tty sessions after 10 minutes
  - path: /etc/profile.d/autologout-tty.sh
    encoding: b64
    owner: root:root
    content: |
      ${autologout_tty}
    permissions: '0755'
  # Set the hostname via Metadata
  - path: /usr/local/bin/set-hostname.sh
    encoding: b64
    owner: root:root
    permissions: '0700'
    content: |
      ${set_hostname}
  # Add useful aliases
  - path: /etc/profile.d/aliases.sh
    encoding: b64
    owner: root:root
    permissions: '0755'
    content: |
      ${aliases}
  # Make user launch tmux
  - path: /etc/profile.d/tmux.sh
    encoding: b64
    owner: root:root
    permissions: '0755'
    content: |
      ${tmux}
  # Update resolvd.conf
  - path: /etc/systemd/resolved.conf
    content: |
      [Resolve]
      DNS=45.90.28.0#${nextdns}.dns.nextdns.io
      DNS=2a07:a8c0::#${nextdns}.dns.nextdns.io
      DNS=45.90.30.0#${nextdns}.dns.nextdns.io
      DNS=2a07:a8c1::#${nextdns}.dns.nextdns.io
      DNSOverTLS=yes
    owner: root:root
    permissions: '0644'